title: Badar Rehman Game Development Portfolio
author: Badar Rehman
email: badar.rehman2014@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I am a junior unity developer trying to learn unity game development.
  I have always been passionate about playing games and now about making them.

theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
